// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// run_constancy
LogicalVector run_constancy(arma::vec x, int n, double delta_max, int method);
RcppExport SEXP m181_run_constancy(SEXP xSEXP, SEXP nSEXP, SEXP delta_maxSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type delta_max(delta_maxSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(run_constancy(x, n, delta_max, method));
    return rcpp_result_gen;
END_RCPP
}
// run_mean
NumericVector run_mean(arma::vec x, int n);
RcppExport SEXP m181_run_mean(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mean(x, n));
    return rcpp_result_gen;
END_RCPP
}
// run_median
NumericVector run_median(arma::vec x, int n);
RcppExport SEXP m181_run_median(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(run_median(x, n));
    return rcpp_result_gen;
END_RCPP
}
// run_sd
NumericVector run_sd(arma::vec x, int n);
RcppExport SEXP m181_run_sd(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(run_sd(x, n));
    return rcpp_result_gen;
END_RCPP
}
// run_max
NumericVector run_max(arma::vec x, int n);
RcppExport SEXP m181_run_max(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(run_max(x, n));
    return rcpp_result_gen;
END_RCPP
}
// run_min
NumericVector run_min(arma::vec x, int n);
RcppExport SEXP m181_run_min(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(run_min(x, n));
    return rcpp_result_gen;
END_RCPP
}
// run_mad
NumericVector run_mad(arma::vec x, int n, double scale_factor);
RcppExport SEXP m181_run_mad(SEXP xSEXP, SEXP nSEXP, SEXP scale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor(scale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mad(x, n, scale_factor));
    return rcpp_result_gen;
END_RCPP
}
// count_sign_change
NumericVector count_sign_change(arma::vec x, int n);
RcppExport SEXP m181_count_sign_change(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(count_sign_change(x, n));
    return rcpp_result_gen;
END_RCPP
}
