# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.run_constancy <- function(x, n, delta_max, method) {
    .Call('m181_run_constancy', PACKAGE = 'm181', x, n, delta_max, method)
}

.run_mean <- function(x, n) {
    .Call('m181_run_mean', PACKAGE = 'm181', x, n)
}

.run_median <- function(x, n) {
    .Call('m181_run_median', PACKAGE = 'm181', x, n)
}

.run_sd <- function(x, n) {
    .Call('m181_run_sd', PACKAGE = 'm181', x, n)
}

.run_max <- function(x, n) {
    .Call('m181_run_max', PACKAGE = 'm181', x, n)
}

.run_min <- function(x, n) {
    .Call('m181_run_min', PACKAGE = 'm181', x, n)
}

.run_mad <- function(x, n, scale_factor = 1.4826) {
    .Call('m181_run_mad', PACKAGE = 'm181', x, n, scale_factor)
}

.count_sign_change <- function(x, n) {
    .Call('m181_count_sign_change', PACKAGE = 'm181', x, n)
}

